"""heart.py — NestedHeart: a smaller coherent model running at the meridian.

User's v0.8.55+ design directive: the outermost shell of the torus
contains the biggest envelope (eventually DeepSeek-V3, V3.1, V4-Pro);
shell 0 contains the heart. The heart is a small, already-coherent
model whose contribution shapes the outer's hidden state at one
designated insertion layer (the meridian).

For the first measurements (and until V3 lands locally), the heart is
Qwen2.5-1.5B-Instruct — already Holoritized, dense (so no inner router
to coordinate with), fits in ~1 GiB on the 4 GiB card. Later, the heart
is swapped to a Zion'iel-MoE without touching this file.

The mechanism:

    outer layer 0 → 1 → ... → M-1 → [project hidden into heart's dim]
                                        → [heart forward (its own layers
                                           + own KV cache)]
                                        → [project back to outer's dim]
                                        → blend with α
                                        → outer layer M+1 → ... → output

The W_in / W_out projections start random-orthogonal: they preserve
hidden-state norms in the overlapping subspace so the heart's
contribution is non-trivial but bounded. They become trainable in the
routing-distillation phase, when we want the heart's voice to align
with the outer's expert-routing structure rather than just perturb it.

The heart's KV cache is independent of the outer's. Each decode step
appends to both. resetkv() is the chat-boundary primitive.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Callable, Optional
import torch


def _random_orthogonal(d_in: int, d_out: int, *,
                       device: Optional[torch.device] = None,
                       dtype: torch.dtype = torch.float16,
                       seed: int = 0) -> torch.Tensor:
    """A (d_in × d_out) semi-orthogonal projection.

    Generated by QR-decomposing a random Gaussian of size max(d_in, d_out)²
    and slicing. Preserves norms in the overlapping subspace: if d_in <
    d_out the result has orthonormal columns; if d_in > d_out it has
    orthonormal rows; if equal it's a rotation.

    Initializing the in/out projections this way means the heart's
    perturbation is bounded (||y|| ≤ ||x||) at α=1, which is exactly
    what we want for a first-cut "does the heart matter?" measurement —
    we don't want the heart to either vanish or explode on the first try.
    """
    g = torch.Generator(device="cpu").manual_seed(seed)
    M = torch.randn(max(d_in, d_out), max(d_in, d_out), generator=g)
    Q, _ = torch.linalg.qr(M)
    P = Q[:d_in, :d_out].contiguous()
    if device is not None:
        P = P.to(device, non_blocking=True)
    return P.to(dtype)


@dataclass
class NestedHeart:
    """A smaller model run at the outer MoE's meridian.

    Construction:
        heart = NestedHeart(
            heart_forward = lambda hidden, pos, kv: ...,
            heart_hidden_dim = 1536,       # Qwen2.5-1.5B's hidden
            outer_hidden_dim = 2048,       # Qwen3-Coder-30B's hidden
            insertion_layer = 24,          # outer's meridian
            alpha = 0.5,
        )

    Wired into the outer's forward_one_token by calling
        x = heart.at_layer(x, outer_layer_idx, position)
    after each outer layer's compute. At outer layer != M this is a
    no-op passthrough. At outer layer == M the heart's contribution is
    blended in as a residual.

    heart_forward is the callable that runs the heart's full forward
    on one token's hidden state. Its signature:

        heart_forward(hidden, position, kv_cache) -> hidden

    For Qwen2.5-1.5B loaded via HF transformers, this would wrap the
    model's `.forward()` with hidden-state input/output (instead of
    token-id input). For a future Zion'iel-MoE, the same callable
    interface holds; only the implementation changes.
    """
    heart_forward: Callable
    heart_hidden_dim: int
    outer_hidden_dim: int
    insertion_layer: int
    alpha: float = 0.5
    W_in:  Optional[torch.Tensor] = None   # (outer_hidden, heart_hidden)
    W_out: Optional[torch.Tensor] = None   # (heart_hidden, outer_hidden)
    kv_cache: dict = field(default_factory=dict)
    device: Optional[torch.device] = None
    dtype: torch.dtype = torch.float16
    # Estimate of the heart's resident MiB on GPU (used by vram_budget
    # to shrink the streamer's tier sizes). 0 for stub hearts.
    heart_resident_mb_estimate: int = 0
    # telemetry
    n_calls: int = 0
    n_passthrough: int = 0

    def __post_init__(self):
        if self.W_in is None:
            self.W_in = _random_orthogonal(
                self.outer_hidden_dim, self.heart_hidden_dim,
                device=self.device, dtype=self.dtype, seed=0)
        if self.W_out is None:
            self.W_out = _random_orthogonal(
                self.heart_hidden_dim, self.outer_hidden_dim,
                device=self.device, dtype=self.dtype, seed=1)

    def at_layer(self, x_outer: torch.Tensor, outer_layer: int,
                 position: int) -> torch.Tensor:
        """Pass through for layers != M; blend heart's output at M.

        x_outer shape: (T, outer_hidden_dim) — typically T=1 for decode.
        Returns same shape; identity at non-insertion layers."""
        self.n_calls += 1
        if outer_layer != self.insertion_layer:
            self.n_passthrough += 1
            return x_outer
        x_heart = x_outer.to(self.dtype) @ self.W_in
        y_heart = self.heart_forward(x_heart, position, self.kv_cache)
        y_outer = y_heart @ self.W_out
        return x_outer + self.alpha * y_outer.to(x_outer.dtype)

    def reset_kv(self):
        """Wipe the heart's KV cache. Call at chat-boundary / new prompt."""
        self.kv_cache.clear()

    def telemetry(self) -> dict:
        return {
            "calls": self.n_calls,
            "passthrough": self.n_passthrough,
            "insertions": self.n_calls - self.n_passthrough,
            "insertion_layer": self.insertion_layer,
            "alpha": self.alpha,
            "W_in_shape": tuple(self.W_in.shape),
            "W_out_shape": tuple(self.W_out.shape),
            "kv_layers_cached": len(self.kv_cache),
        }


# ─── stub heart for early measurements (does the residual fire?) ─────────

def make_noise_stub_heart(heart_hidden_dim: int, outer_hidden_dim: int,
                          insertion_layer: int, *,
                          alpha: float = 0.5,
                          noise_scale: float = 0.1,
                          device: Optional[torch.device] = None,
                          dtype: torch.dtype = torch.float16,
                          seed: int = 1234) -> NestedHeart:
    """A NestedHeart whose heart_forward returns deterministic noise of
    the right shape. Used to verify the residual at M is being applied
    end-to-end without needing a second model loaded.

    "Did the outer's logits change at all between heart=None and
    heart=noise_stub?" — if yes, the wiring is alive. If no, the residual
    isn't reaching the outer's forward pass and we have a bug.
    """
    g = torch.Generator(device="cpu").manual_seed(seed)
    def heart_forward(hidden, position, kv_cache):
        # deterministic per-position noise so two runs with the same
        # seed produce identical results (necessary for measurement)
        local_g = torch.Generator(device="cpu").manual_seed(seed + position)
        z = torch.randn(*hidden.shape, generator=local_g) * noise_scale
        return z.to(hidden.device, dtype=hidden.dtype)
    return NestedHeart(
        heart_forward=heart_forward,
        heart_hidden_dim=heart_hidden_dim,
        outer_hidden_dim=outer_hidden_dim,
        insertion_layer=insertion_layer,
        alpha=alpha,
        device=device,
        dtype=dtype,
    )


# ─── real heart: Qwen2.5-1.5B-Instruct (hidden-state-in / hidden-state-out) ──

def make_qwen_heart(model_path: str,
                    outer_hidden_dim: int,
                    insertion_layer: int,
                    *,
                    alpha: float = 0.5,
                    device: Optional[torch.device] = None,
                    dtype: torch.dtype = torch.float16) -> "NestedHeart":
    """Load a Qwen2.x model as the heart's substance.

    Built for Qwen2.5-1.5B-Instruct (hidden=1536, 28 layers) but the
    hidden_size + layer count are read from the model config, so swapping
    in Qwen2.5-3B-Instruct (hidden=2048) or Qwen2.5-0.5B (hidden=896)
    works without code changes.

    Contract — the returned NestedHeart's heart_forward closure:

        hidden: (T, heart_hidden)    — already projected from outer dim
        position: int                — outer's absolute decode position
        kv_cache: dict               — stash for the heart's own KV state
        returns (T, heart_hidden)    — post-final-norm hidden state

    Heart's KV state lives at `kv_cache["hf_cache"]` as a transformers
    DynamicCache; NestedHeart.reset_kv() drops it so the next call starts
    fresh. The lm_head is removed (we never decode tokens at the heart).

    `model_path` accepts either a HF hub id ("Qwen/Qwen2.5-1.5B-Instruct")
    or an absolute path to a snapshot directory.
    """
    from transformers import AutoModelForCausalLM
    try:
        from transformers.cache_utils import DynamicCache
    except ImportError:
        from transformers import DynamicCache  # very new transformers

    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    full = AutoModelForCausalLM.from_pretrained(
        model_path, torch_dtype=dtype, low_cpu_mem_usage=True)
    inner = full.model  # the Qwen2Model: embed_tokens + layers + norm
    # We feed inputs_embeds, never input_ids → lm_head is dead weight.
    try: del full.lm_head
    except Exception: pass
    inner = inner.to(device).eval()

    heart_hidden = int(inner.config.hidden_size)
    param_mb = int(sum(p.numel() * p.element_size()
                       for p in inner.parameters()) / 1024**2)

    @torch.inference_mode()
    def heart_forward(hidden: torch.Tensor, position: int,
                      kv_cache: dict) -> torch.Tensor:
        # hidden: (T, heart_hidden) — usually T=1 in decode
        if hidden.dim() == 1:
            hidden = hidden.unsqueeze(0)
        T = hidden.shape[0]
        inputs_embeds = hidden.to(device=device, dtype=inner.dtype).unsqueeze(0)
        position_ids = torch.arange(position, position + T,
                                    device=inputs_embeds.device).unsqueeze(0)
        cache = kv_cache.get("hf_cache")
        if cache is None:
            cache = DynamicCache()
            kv_cache["hf_cache"] = cache
        out = inner(
            inputs_embeds=inputs_embeds,
            position_ids=position_ids,
            past_key_values=cache,
            use_cache=True,
            return_dict=True,
        )
        hs = out.last_hidden_state.squeeze(0)   # (T, H)
        return hs.to(hidden.dtype)

    heart = NestedHeart(
        heart_forward=heart_forward,
        heart_hidden_dim=heart_hidden,
        outer_hidden_dim=outer_hidden_dim,
        insertion_layer=insertion_layer,
        alpha=alpha,
        device=device,
        dtype=dtype,
        heart_resident_mb_estimate=param_mb,
    )
    # Stash the inner model on the NestedHeart so it isn't garbage-collected
    # the moment make_qwen_heart returns. The heart_forward closure already
    # holds a reference, but pinning it on the dataclass makes inspection
    # trivial (heart._inner) for debugging.
    heart.__dict__["_inner"] = inner
    return heart


# ─── synthetic self-test (no model load) ─────────────────────────────────

def _selftest():
    """Build a NestedHeart with random projections and a noise stub,
    pass synthetic hidden states through it, assert pass-through at
    non-insertion layers and modification at the insertion layer."""
    OUTER_H, HEART_H, M = 2048, 1536, 24
    heart = make_noise_stub_heart(HEART_H, OUTER_H, M,
                                   alpha=0.5, noise_scale=0.1)
    x = torch.randn(1, OUTER_H, dtype=torch.float16)
    # pass-through at non-insertion layer
    y_pass = heart.at_layer(x, outer_layer=10, position=0)
    assert torch.equal(x, y_pass), "non-insertion layer must passthrough"
    # modification at insertion layer
    y_mod = heart.at_layer(x, outer_layer=M, position=0)
    assert not torch.equal(x, y_mod), "insertion layer must modify"
    delta = (y_mod - x).abs().mean().item()
    assert delta > 0.0, "residual must be nonzero"
    # telemetry sanity
    tel = heart.telemetry()
    assert tel["insertions"] == 1, f"expected 1 insertion, got {tel}"
    assert tel["passthrough"] == 1, f"expected 1 passthrough, got {tel}"
    print(f"[heart-selftest] PASS")
    print(f"  outer_hidden={OUTER_H}, heart_hidden={HEART_H}, M={M}")
    print(f"  mean(|y_mod - x|) at M={M}: {delta:.5f}")
    print(f"  telemetry: {tel}")


if __name__ == "__main__":
    _selftest()
